### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by deborah-ufw** [storybookjs/addon-styling-webpack#14]
### Describe the bug

In IOS Macbook Pro running Sierra, running the  addon-styling-webpack and selecting Less in the configuration results in error immediately upon completion of all the scripts.

All of the default Storybook components (button, header, page) have the same error (below).

Changed button.css to button.less and restarted storybook but problem persists.

```
ERROR in ./src/stories/page.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].oneOf[5].use[2]!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[9].use[1]!./src/stories/page.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(2:7) /Users/deborah/Desktop/ufw/ufw-v6 2023/dev/ufw/src/stories/page.css Unknown word

  1 | 
> 2 |       import API from "!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    |       ^
  3 |       import domAPI from "!../../node_modules/style-loader/dist/runtime/styleDomAPI.js";
  4 |       import insertFn from "!../../node_modules/style-loader/dist/runtime/insertBySelector.js";
 @ ./src/stories/page.css 8:6-335 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-305 77:0-305 78:22-29 78:33-47 78:50-64 55:4-68:5
 @ ./src/stories/Page.jsx 7:0-20
 @ ./src/stories/Page.stories.js 4:0-30 7:13-17
 @ ./src/ lazy ^\.\/.*$ include: (?:\/src(?:\/(?%21\.)(?:(?:(?%21(?:^%7C\/)\.).)*?)\/%7C\/%7C$)(?%21\.)(?=.)[^/]*?\.stories\.(js%7Cjsx%7Cmjs%7Cts%7Ctsx))$ chunkName: [request] namespace object ./stories/Page.stories.js ./stories/Page.stories
 @ ./storybook-stories.js 25:11-29:5
 @ ./storybook-config-entry.js 8:0-50 27:21-29 30:2-33:4 30:58-33:3 32:31-39

preview compiled with 3 errors
=> Failed to build the preview
99% end closing watch compilationWARN Force closed preview build
SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when compiling your code with Webpack.
Run Storybook with --debug-webpack for more information.
    at starter (./node_modules/@storybook/builder-webpack5/dist/index.js:1:9660)
    at starter.next (<anonymous>)
    at Module.start (./node_modules/@storybook/builder-webpack5/dist/index.js:1:11692)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by Integrayshaun** [comment]
Hi @deborah-ufw 👋 

This webpack error means that Less has been double configured. Can you share your main.js file with me please?

**Comment by deborah-ufw** [comment]
hi [Integrayshaun](https://github.com/Integrayshaun)! Thank you for responding so soon! As I went through my dev setup, I realized I selected a wrong configuration at the beginning and started over. Everything works great now and the addon styling webpack is very helpful and works great. :) Many thanks and Happy New Year!!

**Comment by Integrayshaun** [comment]
That's great to hear, @deborah-ufw 🎉 

Happy new year to you as well! Have a wonderful week!
